# Generated by Django 4.2.5 on 2023-09-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_color_orderitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, default='Любой', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
