# Generated by Django 4.2.5 on 2023-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customer_last_name_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/%Y/%m/%d/'),
        ),
    ]
