# Generated by Django 4.2.5 on 2023-11-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_big', models.ImageField(blank=True, null=True, upload_to='galary/%Y/%m/%d/')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='galary/%Y/%m/%d/')),
            ],
        ),
    ]
